import "./globals.css";

import { Manrope } from 'next/font/google'

const ManRope = Manrope({
  subsets: ['latin'],
  display: 'swap',
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={ManRope.className}>
      <body>{children}</body>
    </html>
  );
}
